Version 1.4.2-1
01.03.2010 - Option extract would add an _ at the end of the file name
             when WMO header has a space sign at the end. Fixed.
04.03.2010 - When initializing AFD with 'afd -i' we now delete
             all binary database files, that is everything in
             files/crc, files/incoming/file_mask and
             files/incoming/ls_data is deleted.
12.03.2010 - The detailed information in show_ilog and show_olog
             dialog now also show from which DIR_CONFIG a job comes.
15.03.2010 - Option assemble wrongly puts temp files in $AFD_WORK_DIR.
             Fixed.
22.03.2010 - Process AMG would crash when we reach the maximum number
             of options specified in DIR_CONFIG.
07.04.2010 - In afd_ctrl dialog doing a search did never show
             up any host which used protocol SFTP. Fixed.
24.04.2010 - Added option -H to extract option, to remove the WMO
             header.
30.04.2010 - Fix two errors in accumulate directory options. One that
             it was not initialized correctly when it set for the
             first time with a new directory in DIR_CONFIG. The other
             error was that if the source file is of zero length.
19.05.2010 - set_pw did not always set the password if the passwd
             for a source needed to be set. Fixed.
20.05.2010 - When afdcmd starts, stops, enables or disables it should
             do this in an atomic manner. It just toggled the flag, so
             if the command was called twice at the same time the state
             of the flag would not change. Fixed.
26.05.2010 - In edit_hc dialog show correct Transfer Blocksize.
10.06.2010 - Fix error extract_cus(), that caused delete logs with
             incorrect information.
30.06.2010 - Close output log cache files if process output_log is
             not busy.
05.07.2010 - If SSH server sets attribute bit, ignore it but take
             into account that we have read 4 bytes. Otherwise further
             communication with SSH server will fail because we are
             off by 4 bytes. MySecureShell sets this and AFD fails
             to communicate with it. Fixed.
26.08.2010 - show_olog did not allow user to view data even when the
             option view_data was set in $AFD_WORK_DIR/etc/afd.users.
             Fixed.
05.10.2010 - Added editing function to the afd_info dialog.
12.10.2010 - Reset FTP server reply when we reconnect when changing
             user.
             openssh for a long enough time. In case it is still
             required one can enable it at compile time by setting
             _WITH_FALLBACK_TO_RSH_NO in afdsetup.h.
13.10.2010 - Added %T time modifier for option subject.
             properly in afd init script.
19.10.2010 - Make init scripts more LSB conform.

diff --git a/scripts/afd.in b/scripts/afd.in
--- a/scripts/afd.in
+++ b/scripts/afd.in
@@ -8,6 +8,9 @@
 #              and/or SCP. It collects files via FTP, FTPS, SFTP, HTTP \
 #              and/or HTTPS.
 ### BEGIN INIT INFO
+# Provides: afd
+# Required-Start: $local_fs
+# Required-Stop: $local_fs
 # Should-Start: $local_fs $network $time $remote_fs
 # Should-Stop: $local_fs $network $time $remote_fs
 # Default-Start: 2 3 5
@@ -48,28 +51,42 @@ case "$1" in
 	   then
 	      echo -n "Starting AFD for $afduser : "
 	      su - $afduser -c "afd -a"
-	      if [ $? -eq 0 ]
-	      then
-	         RETVAL=0
-	         touch /var/lock/subsys/afd.$afduser
-	         echo "Done"
-	      else
-	         echo "Failed"
-	      fi
+	      case $? in
+	         0)
+	            RETVAL=0
+	            touch /var/lock/subsys/afd.$afduser
+	            echo "Done"
+	            ;;
+	         6) # AFD is disbled by system admin
+	            RETVAL=0
+	            touch /var/lock/subsys/afd.$afduser
+	            echo "Done"
+	            ;;
+	         *)
+	            echo "Failed"
+	            ;;
+	      esac
 	   else
 	      counter=0
 	      for afddir in $AFD_WORK_DIR_LIST
 	      do
 	         echo -n "Starting AFD for $afduser in $afddir : "
 	         su - $afduser -c "afd -w $afddir -a"
-	         if [ $? -eq 0 ]
-	         then
-	            RETVAL=0
-	            touch /var/lock/subsys/afd.$afduser-$counter
-	            echo "Done"
-	         else
-	            echo "Failed"
-	         fi
+	         case $? in
+	            0)
+	               RETVAL=0
+	               touch /var/lock/subsys/afd.$afduser-$counter
+	               echo "Done"
+	               ;;
+	            6) # AFD is disbled by system admin
+	               RETVAL=0
+	               touch /var/lock/subsys/afd.$afduser-$counter
+	               echo "Done"
+	               ;;
+	            *)
+	               echo "Failed"
+	               ;;
+	         esac
 	         counter=`expr "$counter" + 1`
 	      done
 	   fi
@@ -160,14 +177,21 @@ case "$1" in
 	      then
 	         echo -n "Starting AFD for $afduser : "
 	         su - $afduser -c "afd -a"
-	         if [ $? -eq 0 ]
-	         then
-	            RETVAL=0
-	            touch /var/lock/subsys/afd.$afduser
-	            echo "Done"
-	         else
-	            echo "Failed"
-	         fi
+	         case $? in
+	            0)
+	               RETVAL=0
+	               touch /var/lock/subsys/afd.$afduser
+	               echo "Done"
+	               ;;
+	            6) # AFD is disbled by system admin
+	               RETVAL=0
+	               touch /var/lock/subsys/afd.$afduser
+	               echo "Done"
+	               ;;
+	            *)
+	               echo "Failed"
+	               ;;
+	         esac
 	         rm -f /var/lock/subsys/restart_afd.$afduser
 	      else
 	         su - $afduser -c "afd -S"
@@ -175,14 +199,21 @@ case "$1" in
 	         then
 	            sleep 2
 	            su - $afduser -c "afd -a"
-	            if [ $? -eq 0 ]
-	            then
-	               RETVAL=0
-	               touch /var/lock/subsys/afd.$afduser
-	               echo "Done"
-	            else
-	               echo "Failed"
-	            fi
+	            case $? in
+	               0)
+	                  RETVAL=0
+	                  touch /var/lock/subsys/afd.$afduser
+	                  echo "Done"
+	                  ;;
+	               6) # AFD is disbled by system admin
+	                  RETVAL=0
+	                  touch /var/lock/subsys/afd.$afduser
+	                  echo "Done"
+	                  ;;
+	               *)
+	                  echo "Failed"
+	                  ;;
+	            esac
 	         fi
 	      fi
 	   else
@@ -193,14 +224,21 @@ case "$1" in
 	         then
 	            echo -n "Starting AFD for $afduser : "
 	            su - $afduser -c "afd -w $afddir -a"
-	            if [ $? -eq 0 ]
-	            then
-	               RETVAL=0
-	               touch /var/lock/subsys/afd.$afduser-$counter
-	               echo "Done"
-	            else
-	               echo "Failed"
-	            fi
+	            case $? in
+	               0)
+	                  RETVAL=0
+	                  touch /var/lock/subsys/afd.$afduser-$counter
+	                  echo "Done"
+	                  ;;
+	               6) # AFD is disbled by system admin
+	                  RETVAL=0
+	                  touch /var/lock/subsys/afd.$afduser-$counter
+	                  echo "Done"
+	                  ;;
+	               *)
+	                  echo "Failed"
+	                  ;;
+	            esac
 	            rm -f /var/lock/subsys/restart_afd.$afduser-$counter
 	         else
 	            su - $afduser -c "afd -w $afddir -S"
@@ -208,14 +246,21 @@ case "$1" in
 	            then
 	               sleep 2
 	               su - $afduser -c "afd -w $afddir -a"
-	               if [ $? -eq 0 ]
-	               then
-	                  RETVAL=0
-	                  touch /var/lock/subsys/afd.$afduser-$counter
-	                  echo "Done"
-	               else
-	                  echo "Failed"
-	               fi
+	               case $? in
+	                  0)
+	                     RETVAL=0
+	                     touch /var/lock/subsys/afd.$afduser-$counter
+	                     echo "Done"
+	                     ;;
+	                  6) # AFD is disbled by system admin
+	                     RETVAL=0
+	                     touch /var/lock/subsys/afd.$afduser-$counter
+	                     echo "Done"
+	                     ;;
+	                  *)
+	                     echo "Failed"
+	                     ;;
+	               esac
 	            fi
 	         fi
 	         counter=`expr "$counter" + 1`
@@ -280,6 +325,7 @@ case "$1" in
   status)
 	NOT_RUNNING=""
 	IS_RUNNING=""
+	IS_DISABLED=""
 	for afduser in $AFD_USERS
 	do
 	   TMP_MULTI_DIR_FILE="/tmp/afd_multi_dirs.$$"
@@ -292,7 +338,13 @@ case "$1" in
 	      RETVAL=$?
 	      if [ $RETVAL -ne 5 ]
 	      then
-	         NOT_RUNNING="`echo $NOT_RUNNING` $afduser"
+	         su - $afduser -c "ls $AFD_WORK_DIR/etc/NO_AUTO_RESTART > /dev/null 2>&1"
+	         if [ $? = 0 ]
+	         then
+	            IS_DISABLED="`echo $IS_DISABLED` $afduser"
+	         else
+	            NOT_RUNNING="`echo $NOT_RUNNING` $afduser"
+	         fi
 	      else
 	         IS_RUNNING="`echo $IS_RUNNING` $afduser"
 	      fi
@@ -304,7 +356,12 @@ case "$1" in
 	         RETVAL=$?
 	         if [ $RETVAL -ne 5 ]
 	         then
-	            NOT_RUNNING="`echo $NOT_RUNNING` $afduser[$afddir]"
+	            if [ -f $afddir/etc/NO_AUTO_RESTART ]
+	            then
+	               IS_DISABLED="`echo $IS_DISABLED` $afduser[$afddir]"
+	            else
+	               NOT_RUNNING="`echo $NOT_RUNNING` $afduser[$afddir]"
+	            fi
 	         else
 	            IS_RUNNING="`echo $IS_RUNNING` $afduser[$afddir]"
 	         fi
@@ -314,7 +371,12 @@ case "$1" in
 	done
 	if [ "$NOT_RUNNING" = "" ]
 	then
-	   echo "AFD for${IS_RUNNING} is running."
+	   if [ "$IS_DISABLED" = "" ]
+	   then
+	      echo "AFD for${IS_RUNNING} is running."
+	   else
+	      echo "AFD for${IS_RUNNING} is running and for${IS_DISABLED} it is disabled."
+	   fi
 	   RETVAL=0
 	else
 	   echo "AFD for${NOT_RUNNING} is NOT active."
